// Files in this folder are generated by the Blender WebGPU Export Addon.
// They contain scene data from the user and are not covered by the addon's license.
engine.scene.data.info.viewport = engine.scene.data.info.viewport || {}
engine.scene.data.info.viewport.color = [0.05087608844041824, 0.05087608844041824, 0.05087608844041824]
engine.scene.data.info.viewport.alpha = true
engine.scene.data.info.camera = 'Camera'
engine.scene.data.info.files = [
	'cameras/Camera',
	'meshes/market',
	'meshes/marketstand_table',
	'meshes/Fern',
	'meshes/birch_generated',
	'meshes/market.001',
	'meshes/Circle.001',
	'meshes/shelf',
	'meshes/shelf.001',
	'meshes/shelf.002',
	'meshes/woodcart',
	'meshes/bench',
	'meshes/well.001',
	'meshes/Cube',
	'meshes/Cube.001',
	'meshes/well.002',
	'meshes/book',
	'meshes/book.001',
	'meshes/book.002',
	'meshes/book.003',
	'meshes/book.004',
	'meshes/book.005',
	'meshes/book.006',
	'meshes/book.007',
	'meshes/book.008',
	'meshes/book.009',
	'meshes/birch_leaves_generated',
	'materials/default',
	'materials/Material',
	'materials/M_B_Green',
	'materials/white',
	'materials/Material.003',
	'materials/Clay',
	'materials/Material.001',
	'materials/Material.004',
	'lights/Light',
	'lights/Light.001',
	'lights/Light.002'
]